### ISSUE TITLE
Make thumbnails Horizontally scrollable accross the screen.

### ISSUE THREAD

**Issue by IamLRBA** [IamLRBA/LRBA-FusionCraft-STUDIOS-Architecture-Website#2]
# Description of the issue

Currently, the thumbnails start from almost the center of the bottom of the page and spread linearly to the right of the page, horizontally. To view thumbnails on the far right, the page instead moves away from the screen towards the left in order to reveal the other thumbnails not shown, on the line. 

##  Solution

Create a method that makes the thumbnails able to scroll (in the same manner as a horizontal scroll bar ) to make sure the thumbnails not showing on the screen are revealed by moving the first ones before each thumbnail (on it's left) towards the left side of the screen. This means the Thumbnails should be able to completely move across the screen until the last on on the farthest right appears on the screen. Then of course, they should be scrolled be able to be scrolled back into position (as they were).  
 
## 📋 Step by step guide to do a contribution

If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow.
A more detailed general documentation of the GitHub PR workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- Claim this issue: Comment below that you are interested in working on the issue
-
- Wait for assignment: A community member with the given rights will add you as an assignee of the issue
- Fork the repository: You can do that in GitHub (by simply clicking the 'fork' button).
- Check out the forked repository
- Create a feature branch for the issue. We do not have a hard naming definition for branches but it is best practice to prefix the branch name with the issue id.
- Solve the issue in your branch.
- Commit your changes: to your branch
- Start a Pull Request (PR): in the LRBA-FusionCraft-STUDIOS-Architecture-Website  repository
- Check GitHub Actions: Several GitHub Actions will be triggered automatically for each PR. If a GitHub Action fails and you do not understand the cause of that error do not hesitate to add a comment to the PR and ask the community for support.
- Wait for reviews: Members of the community will review your PR. If a reviewer finds any missing pieces or a problem, he or she will start a discussion with you and describe the next steps for solving the problem.
- You did it 🎉: We will merge the fix in the develop branch. Thanks for being part of our community as an open-source contributor ❤️

**Comment by FucFeFa** [comment]
Hi, I would like to work on this issue! Could you please assign it to me?
