### ISSUE TITLE
Make a dropdown burger menu

### ISSUE THREAD

**Issue by IamLRBA** [IamLRBA/LRBA-FusionCraft-STUDIOS-Architecture-Website#3]
# Description of the issue

Currently, the website displays the menu items; "Home, About, Services and Contact" in a linear manner.

## Solution

Create a burger menu with an appropriate minimal design burger menu icon that should be able to drop down and display the menu items listed in the description above.
Provide appropriate CSS designs for said menu items including hover effects.

## 📋 Step by step guide to do a contribution

If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow.
A more detailed general documentation of the GitHub PR workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- **Claim this issue**: Comment below that you are interested in working on the issue

- **Wait for assignment**: A community member with the given rights will add you as an assignee of the issue

- **Fork the repository**: You can do that in GitHub (by simply clicking the 'fork' button).

- Check out the forked repository

- Create a feature branch for the issue. We do not have a hard naming definition for branches but it is best practice to prefix the branch name with the issue id.

- Solve the issue in your branch.

- **Commit your changes**: to your branch

- **Start a Pull Request (PR)**: in the LRBA-FusionCraft-STUDIOS-Architecture-Website  repository

- **Check GitHub Actions**: Several GitHub Actions will be triggered automatically for each PR. If a GitHub Action fails and you do not understand the cause of that error do not hesitate to add a comment to the PR and ask the community for support.

- **Wait for reviews**: Members of the community will review your PR. If a reviewer finds any missing pieces or a problem, he or she will start a discussion with you and describe the next steps for solving the problem.

- **You did it 🎉**: We will merge the fix in the develop branch. Thanks for being part of our community as an open-source contributor ❤️

**Comment by WasThatRudy** [comment]
Hi there! I can help with this issue. Could you please assign it to me? Looking forward to contributing!

**Comment by IamLRBA** [comment]
Done assigning you @rudrakshass, Happy coding buddy ✌️
